# Generated by Django 4.0.3 on 2022-04-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.CharField(max_length=500)),
                ('antwort', models.CharField(max_length=4000)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preis', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeistungsKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fahrzeug', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='leistung',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool_manager.leistungskategorie'),
        ),
    ]
